### PR TITLE
fix memory leak with command image init

### LINKED ISSUE #480: Memory Leak in clEnqueueMapImage
I've observed a memory leak when using clEnqueueMapImage. Following is the reproducing code:
```cpp
#define CL_TARGET_OPENCL_VERSION 120
#include <CL/cl.h>

#include <array>
#include <iostream>
#include <optional>
#include <variant>

constexpr size_t platform_choice = 0;
constexpr size_t device_choice = 0;

auto get_cl_device() -> std::variant<cl_int, cl_device_id> {
	std::array<cl_platform_id, 16> platform_ids;
	cl_uint platform_count;
	cl_int error =
	    clGetPlatformIDs(static_cast<cl_uint>(platform_ids.size()),
			     platform_ids.data(), &platform_count);
	if (error != CL_SUCCESS) {
		std::puts("GetPlatformsFailed");
		return error;
	}

	if (platform_count == 0) {
		std::puts("no platforms found");
		return 0;
	}

	std::array<cl_device_id, 16> device_ids;
	cl_uint device_count;
	error =
	    clGetDeviceIDs(platform_ids[platform_choice], CL_DEVICE_TYPE_ALL,
			   static_cast<cl_uint>(device_ids.size()),
			   device_ids.data(), &device_count);
	if (error != CL_SUCCESS) {
		std::puts("get devices failed");
		return error;
	}

	if (device_count == 0) {
		std::puts("no devices found");
		return 0;
	}
	return device_ids[device_choice];
}

auto free_queue(cl_command_queue queue) {
	clFlush(queue);
	clFinish(queue);
	clReleaseCommandQueue(queue);
}

int main() {
	auto device = std::get<cl_device_id>(get_cl_device());
	// create buffer
	using arr_ty = std::int32_t;
	std::array<arr_ty, 100> input_array;

	cl_int error;
	auto ctx =
	    clCreateContext(nullptr, 1, &device, nullptr, nullptr, &error);
	if (ctx == nullptr) return error;

	cl_image_format imageFormat{CL_RGB, CL_SIGNED_INT32};

	cl_image_desc imageDesc{};

	imageDesc.image_type = CL_MEM_OBJECT_IMAGE1D;
	imageDesc.image_width = 100;
	imageDesc.image_height = 0;
	imageDesc.image_depth = 0;

	size_t origin[4] = {0, 0, 0, 0};
	size_t region[3] = {imageDesc.image_width, 1, 1};
	size_t offset[3] = {0, 0, 0};

	auto command_queue = clCreateCommandQueue(ctx, device, 0, &error);
	for (int i = 0; i < 42; ++i) {
		auto image = clCreateImage(ctx, CL_MEM_READ_ONLY, &imageFormat,
					   &imageDesc, nullptr, &error);
		if (error != CL_SUCCESS) {
			std::cout << "problem with create image\n";
			return error;
		}

		size_t row_pitch, slice_pitch;
		auto mem = clEnqueueMapImage(
		    command_queue, image, CL_TRUE, CL_MAP_READ, origin, region,
		    &row_pitch, &slice_pitch, 0, nullptr, nullptr, &error);
		if (error != CL_SUCCESS) {
			std::cout << "problem with enqueue map image\n";
			return error;
		}

		error = clEnqueueUnmapMemObject(command_queue, image, mem, 0,
						nullptr, nullptr);
		if (error != CL_SUCCESS) {
			std::cout << "problem with enqueue unmap\n";
			return error;
		}

		clReleaseMemObject(image);
	}
	free_queue(command_queue);
	clReleaseContext(ctx);
}
```
When run I with `CLVK_LOG=4` environment variable I see 43 objects not reaching 0 refcounts, 42 with 1 count and 1 with 42 counts. I believe the 42 count object is the context due to seeing lines like 
```
[CLVK] clReleaseContext: context = 0x55e14c689770
# and
[CLVK] release: obj = 0x55e14c689760, refcount now 42
```
but the pointers are 16 bytes apart.

The 1 count objects are likely events since I've seen the ptr appear in logs like 
```
[CLVK] enqueue_command: enqueued command 0x55e14c4a5e90, event 0x55e14c6c7960
# and
[CLVK] cvk_event::set_status: event = 0x55e14c6c7960, status = 0
```

I'm trying to hunt it down, but any help would be appreciated.

### PR DESCRIPTION
**Pull request by rjodinchr**
During command image init construction, we call enqueue_command with a _cl_event in parameter.
We will retain this event in enqueue_command because we associate this pattern as an event from userspace that needs to be retained automatically.
But we have no release associated with this.

Fix #480

### CODE REVIEW

File: src/queue.cpp [hunk 1]
```diff
@@ -102,7 +102,13 @@ cl_int cvk_command_queue::satisfy_data_dependencies(cvk_command* cmd) {
         if (err != CL_SUCCESS) {
             return err;
         }
-        tracker.set_event(icd_downcast(initev));
+        auto downcastev = icd_downcast(initev);
+        tracker.set_event(downcastev);
+
+        // the event has been retained by `enqueue_command` thinking it is a
+        // userspace event. But as it will not be given to the user, it needs to
+        // be released here to avoid a memory leak.
```
Comment (kpet) [inline src/queue.cpp:110]:
```suggestion
        // The event has been retained by `enqueue_command` to give its user
        // a refcount on the event. The tracker will request a refcount so we need
        // to give up the one we got from `enqueue_command`.
```

**Review by kpet — COMMENTED** [review]
Looks good with a few tweaks to the comment.

File: src/queue.cpp [hunk 2]
```diff
@@ -102,7 +102,13 @@ cl_int cvk_command_queue::satisfy_data_dependencies(cvk_command* cmd) {
         if (err != CL_SUCCESS) {
             return err;
         }
-        tracker.set_event(icd_downcast(initev));
+        auto downcastev = icd_downcast(initev);
+        tracker.set_event(downcastev);
+
+        // The event has been retained by `enqueue_command` to give its user
+        // a refcount on the event. The tracker will request a refcount so we need
+        // to give up the one we got from `enqueue_command`.
```
Comment (kpet) [inline src/queue.cpp:110]:
```suggestion
        // a refcount on the event. The tracker will request a refcount so we
        // need to give up the one we got from `enqueue_command`.
```
